version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - /private/tmp/docker/volumes/mongodb:/data/db
    healthcheck:
      test: "exit 0"
    networks:
      - private
networks:
  private:
    driver: bridge