version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - /private/tmp/docker/volumes/mongodb:/data/db
    healthcheck:
      test: "exit 0"
    networks:
      - private
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /private/tmp/docker/volumes/rabbitmq:/data/rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - private
networks:
  private:
    driver: bridge